<?php
define("DBHOST","127.0.0.1");
define("DBPORT","3306");
define("DBNAME","P_GATEWAY_DEVEL");
define("DBUSER","gw_user");
define("DBPWD","gw_pwd");
define("DBTABLE","PBB_SPPT");
define("DBTABLEKECAMATAN","cppmod_tax_kecamatan");
define("DBTABLEKELURAHAN","cppmod_tax_kecamatan");
?>
