<?php
define("DBHOST","127.0.0.1");
define("DBPORT","3306");
define("DBNAME","GW_PBB_PALEMBANG");
define("DBUSER","gw_user");
define("DBPWD","gw_pbb");
define("DBTABLE","PBB_SPPT");
define("DBTABLEKECAMATAN","PBB.PBB_MASTER_KECAMATAN");
define("DBTABLEKELURAHAN","PBB.PBB_MASTER_KELURAHAN");
?>
